### ISSUE TITLE
bug: CMDLOAD coloring prefix is messed up and shows the raw template

### ISSUE THREAD

**Issue by numselli** [thetayloredman/ProtoBot#463] opened 2022-03-13 02:44 UTC
**Describe the bug**
CMDLOAD coloring prefix is messed up and shows the raw template

**To Reproduce**

1. Run the bot
3. See `[Sat Mar 12 2022 6:39:25 PM] [INFO] [CMDLOAD] {chalk.yellow('[')}CMDLOAD] Beginning initial command load...`
4. View error

**Expected behavior**
the template sting should show the sting with the template filled in

**Actual Behavior**
template sting shows the template not filled in
What actually happened?

**Screenshots**
![image](https://user-images.githubusercontent.com/58607232/158042687-cb81d6e1-965a-44ec-87ca-48a8b4463882.png)

**Comment by thetayloredman** [comment] 2022-03-13 03:36
This does not seem possible to occur...

Examining the code at [`5b320d/src/index.ts` lines 95 to 97](https://github.com/thetayloredman/ProtoBot/blob/5b320dc9f4f37737ff83066fbc34b4ae10b45a95/src/index.ts#L95-L97) shows the prefix is not doubled like shown here. Please confirm your HEAD commit and branch on your local DE?

For now, tagging as wontfix.

**Comment by thetayloredman** [comment] 2022-03-13 03:39
Coming from other information in other screenshots, you are not running the latest commit of ProtoBot. Another log output had shown information with a lot of repeated stack traces, which was fixed in a recent PR merge. Please check `head_branch=main` and `head_commit=5b320d`.

**Closed** 2022-03-13 04:03 UTC
Labels: bug, wontfix

**Comment by thetayloredman** [comment] 2022-03-13 17:07
The problem was confirmed to relate to incorrect execution. They were running `node .`, not the start script.
