### ISSUE TITLE
send help menu in DMs instead

### ISSUE THREAD

**Issue by ada-mon** [thetayloredman/ProtoBot#62] opened 2020-12-02 16:28 UTC
The help menu takes up more than my entire screen on mobile, send it to the user's DMs instead :(

**Comment by thetayloredman** [comment] 2020-12-02 16:32
Oh, this! Already put that in #26.

**Marked as duplicate.**

**Closed by thetayloredman** 2020-12-02 16:32 UTC

**Comment by thetayloredman** [comment] 2020-12-03 18:34
Duplicate of #26
